"""Derive the push-forward fine-tune configs from the benchmark matrix.

For every Train1-10 config (configs/<campaign>/<model>_<kind>.yaml) whose run under
case/train has finished, write configs/push/<campaign>/<model>_<kind>.yaml: the same
recipe with half the epochs, a third of the lr (`LR_DIVISOR`; the schedule is unchanged),
`train.init_from` pointing at that run's ckpts/best.pt, and push-forward on (`PUSH`: one
ungraded step, push probability ramping 0.5 -> 1.0, noise 0.01 on the rest), writing under
case/train_push/. A base that has not finished is
reported and skipped; rerun the script once it has — a generated file is rewritten only
when its content changes. tests/test_push.py checks every shipped file against `derive`.

Usage:
  uv run python case/train_push/make_configs.py [--dry-run] [--only SUBSTR]
"""

import argparse
import json
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
CAMPAIGNS = ("drainage", "gdl", "trapping", "underfill")
PUSH = {"steps": 1, "prob_start": 0.5, "prob_end": 1.0, "noise": 0.01}
LR_DIVISOR = 3  # a fine-tune restarts the base schedule at a third of its peak lr
# Transolver trains without activation checkpointing: 35 GiB instead of 14 on an H200 (143 GiB)
# for a 2x faster step under tf32 (0.49 -> 0.23 s, measured 2026-09-10); the numbers are identical.
NO_CHECKPOINT = ("transolver",)
ROLLOUT_HEAVY = ("abupt",)  # periodic rollout every epochs // 5 instead of every epoch

sys.path.insert(0, str(REPO / "src"))
from poreml.config import Config  # noqa: E402


def finished_best(out_dir: Path) -> Path | None:
    """`ckpts/best.pt` of the newest finished run under a config's out_dir, or None."""
    if not out_dir.is_dir():
        return None
    for meta in sorted(out_dir.glob("*/run_meta.json"), key=lambda p: p.stat().st_mtime, reverse=True):
        best = meta.parent / "ckpts" / "best.pt"
        if json.loads(meta.read_text()).get("status") == "finished" and best.is_file():
            return best
    return None


def derive(base: Config, best: Path) -> Config:
    """The fine-tune config of `base`: half the epochs (and the knobs the protocol ties to the
    epoch count: FNO's and P3D's StepLR; the periodic rollout every epoch, every epochs // 5
    for AB-UPT), a third of the lr (3 significant
    digits; the schedule itself is the base's), weights from `best`, push-forward on, artifacts
    under case/train_push. Everything else — data, split, task, model, the rest of the optimiser
    recipe, metrics, rollout protocol, seed — is the base recipe."""
    epochs = base.train.epochs // 2
    lr = float(f"{base.train.lr / LR_DIVISOR:.3g}")
    train = base.train.model_dump(mode="json")
    train.update(epochs=epochs, lr=lr, init_from=str(best), push_forward=dict(PUSH))
    model = base.model.model_dump(mode="json")
    if base.model.name in NO_CHECKPOINT:
        model["params"] = {**model["params"], "checkpoint": False}
    if train["eval"] is not None:
        # The periodic eval is the rollout alone (2026-09-10, finalise.py selects on it), cheap
        # enough to run every epoch — except for AB-UPT, whose 64-step rollout is the expensive
        # part (40-90 min per eval at 128, ~4 h on underfill): it keeps the base cadence.
        train["eval"]["every"] = max(1, epochs // 5) if base.model.name in ROLLOUT_HEAVY else 1
    if base.model.name == "fno3d":
        train["lr_step_size"] = max(1, epochs // 5)
    if base.model.name == "p3d":
        train["lr_step_size"] = round(epochs * 2 / 3)
    out_dir = str(base.out_dir).replace("case/train/", "case/train_push/", 1)
    return base.updated(name=base.name + "_push", train=train, model=model, out_dir=out_dir)


def render(cfg: Config, base_path: Path, best: Path, base_lr: float) -> str:
    meta = json.loads((best.parents[1] / "run_meta.json").read_text())
    best_epoch = (meta.get("progress", {}).get("best") or {}).get("epoch")
    header = (
        f"# Push-forward fine-tune of {base_path}: generated by case/train_push/make_configs.py, do not edit by hand.\n"
        f"# Starts from {best} (best epoch {best_epoch} of {meta.get('progress', {}).get('epochs_total')}), trains\n"
        f"# {cfg.train.epochs} epochs at lr {cfg.train.lr:g} (base {base_lr:g} / {LR_DIVISOR}); push-forward {PUSH}.\n"
        "# See case/train_push/README.md.\n"
    )
    return header + yaml.safe_dump(cfg.model_dump(mode="json"), sort_keys=False)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dry-run", action="store_true", help="report; write nothing")
    ap.add_argument("--only", default="", help="substring filter on config paths")
    args = ap.parse_args()

    written = unchanged = waiting = 0
    for campaign in CAMPAIGNS:
        for base_path in sorted((REPO / "configs" / campaign).glob("*.yaml")):
            rel = base_path.relative_to(REPO)
            if args.only and args.only not in str(rel):
                continue
            base = Config.from_yaml(base_path)
            best = finished_best(REPO / base.out_dir)
            if best is None:
                print(f"  waiting   {rel}  (no finished run under {base.out_dir})")
                waiting += 1
                continue
            cfg = derive(base, best.relative_to(REPO))
            text = render(cfg, rel, best.relative_to(REPO), base.train.lr)
            target = REPO / "configs" / "push" / campaign / base_path.name
            if target.is_file() and target.read_text() == text:
                print(f"  unchanged {target.relative_to(REPO)}")
                unchanged += 1
                continue
            print(f"  {'would write' if args.dry_run else 'written'}  {target.relative_to(REPO)}  <- {best.relative_to(REPO)}")
            written += 1
            if not args.dry_run:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(text)
    print(f"\n{written} written, {unchanged} unchanged, {waiting} waiting for their base run")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
