"""Derive configs/<study>_push/ from configs/<study>/ for study in (shift, scale).

Same protocol (scheme.yaml), same frozen test data (data.yaml, the split files under
splits/<study>/), same campaigns and models; the only change is the checkpoint: the
push-forward fine-tune's rollout-best weights, `case/train_push/<campaign>/<model>_<kind>/
ckpts/<run>/ckpts/best_rollout.pt` (finalise.py), instead of the base run's `best.pt`.
Outputs land under case/<study>_push/. Rerun after editing configs/<study>/; files are
rewritten only when their text changes.

    uv run python util/configs/make_push_study_configs.py [--dry-run]
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
STUDIES = ("shift", "scale")


def derive_cell(text: str, study: str) -> str:
    push = f"{study}_push"
    out = text
    out = re.sub(rf"^name: {study}_", f"name: {push}_", out, flags=re.M)
    out = out.replace(f"configs/{study}/", f"configs/{push}/")
    out = re.sub(r"^(\s*train_case: )case/train/", r"\1case/train_push/", out, flags=re.M)
    which = r"\1best_rollout                  # the push-forward run's rollout-best epoch (finalise.py), not its one-step best"
    out = re.sub(r"^(\s*which: )best\b.*$", which, out, flags=re.M)
    out = re.sub(rf"^out_dir: case/{study}/", f"out_dir: case/{push}/", out, flags=re.M)
    header = (
        f"# {push}: the {study} study repeated on the push-forward fine-tune's rollout-best checkpoint\n"
        f"# (case/train_push, ckpts/best_rollout.pt) under the same protocol and data as configs/{study}/.\n"
        f"# Generated by util/configs/make_push_study_configs.py from configs/{study}/"
        " — edit the source, not this file.\n"
    )
    return header + out


def derive_shared(text: str, study: str) -> str:
    push = f"{study}_push"
    return (
        f"# Copied for {push} by util/configs/make_push_study_configs.py from configs/{study}/ — identical protocol/data.\n"
        + text.replace(f"configs/{study}/", f"configs/{push}/")
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    written = unchanged = 0
    for study in STUDIES:
        src_root, dst_root = REPO / "configs" / study, REPO / "configs" / f"{study}_push"
        for src in sorted(src_root.rglob("*.yaml")):
            rel = src.relative_to(src_root)
            text = src.read_text()
            new = derive_shared(text, study) if src.name in ("data.yaml", "scheme.yaml") else derive_cell(text, study)
            dst = dst_root / rel
            if dst.is_file() and dst.read_text() == new:
                unchanged += 1
                continue
            written += 1
            print(f"  {'would write' if args.dry_run else 'written'}  {dst.relative_to(REPO)}")
            if not args.dry_run:
                dst.parent.mkdir(parents=True, exist_ok=True)
                dst.write_text(new)
    print(f"{written} written, {unchanged} unchanged")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
